In [1]:
import numpy as np
import sys

In [2]:
# 1d and 2d array

a = np.array([1,2,3])
b = np.array([['foo','hoo'],['woo', 'too']])
print(a)
print()
print(b)

[1 2 3]

[['foo' 'hoo']
 ['woo' 'too']]


In [3]:
print(type(b))

<class 'numpy.ndarray'>


In [5]:
c = np.array([1.5,3.5,'no'])  # here floats are converted to string to maintain homegenity of data types
print(c)

['1.5' '3.5' 'no']


In [6]:
c.dtype

dtype('<U32')

In [7]:
d = np.array([[1,2,3],[11,22]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

## arange, linspace and reshape

In [8]:
e = np.arange(1,20,3)  #start, stop and stepsize
print(e)

[ 1  4  7 10 13 16 19]


In [10]:
f = np.linspace(1,20,10) # start, stop and nos of points
print(f)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [11]:
g = np.reshape(f,(2,5))
print(g)
print()
h = np.reshape(f,(5,2))
print(h)

[[ 1.          3.11111111  5.22222222  7.33333333  9.44444444]
 [11.55555556 13.66666667 15.77777778 17.88888889 20.        ]]

[[ 1.          3.11111111]
 [ 5.22222222  7.33333333]
 [ 9.44444444 11.55555556]
 [13.66666667 15.77777778]
 [17.88888889 20.        ]]


## initializing arrays

In [12]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
rns = np.random.random((2,2))
print(rns)

[[0.25847381 0.5110414 ]
 [0.18229386 0.65272617]]


In [18]:
identity1 = np.eye(3)
print(identity1)
print()
identity2 = np.eye(3,4)
print(identity2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## array attributes

In [20]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [23]:
print(a1.shape)
print(a2.shape)
print(a3.shape)
print()
print(a3)

(10,)
(3, 4)
(2, 2, 2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [25]:
a2.size

12

In [29]:
a2.itemsize

8

## Memory optimization by changing dtype

In [36]:
m1 = np.eye(10)
print(m1)
sys.getsizeof(m1)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


928

In [42]:
m2 = m1.astype('float16')
print(m2)
sys.getsizeof(m2)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


328

In [45]:
m3 = m1.astype('int8')
print(m3)
sys.getsizeof(m3)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


228

## Array Operation

In [48]:
b1 = np.random.randint(-10,10,12)
b2 = np.round(np.linspace(-10,10,12),2)

In [49]:
print(b1)
print(b2)

[-1 -7  7 -1  1 -7 -6 -3 -7 -1  7  8]
[-10.    -8.18  -6.36  -4.55  -2.73  -0.91   0.91   2.73   4.55   6.36
   8.18  10.  ]


In [50]:
print(b1*10)

[-10 -70  70 -10  10 -70 -60 -30 -70 -10  70  80]


In [51]:
print(b1**2)

[ 1 49 49  1  1 49 36  9 49  1 49 64]


In [52]:
print(b1+b2)

[-11.   -15.18   0.64  -5.55  -1.73  -7.91  -5.09  -0.27  -2.45   5.36
  15.18  18.  ]


In [53]:
b1>=0

array([False, False,  True, False,  True, False, False, False, False,
       False,  True,  True])

## Useful Array functions

### round

In [54]:
c1 = np.random.randn(2,3)
print(c1)
print()
print(np.round(c1,3))

[[ 0.46239458  0.70410574  0.78632224]
 [ 0.63100611  0.12560858 -0.5624634 ]]

[[ 0.462  0.704  0.786]
 [ 0.631  0.126 -0.562]]


### min/ max/ sum/ prod / median/ mean/ std / var

In [56]:
c2 = np.arange(1,7).reshape(2,3)

In [57]:
print(c2)

[[1 2 3]
 [4 5 6]]


In [58]:
np.max(c2,axis=0)

array([4, 5, 6])

In [59]:
np.max(c2,axis = 1)

array([3, 6])

In [60]:
np.mean(c2,axis = 1)

array([2., 5.])

In [61]:
np.var(c2,axis = 1)

array([0.66666667, 0.66666667])

In [62]:
np.log(c2)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [63]:
np.log1p(c2)

array([[0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015]])

In [64]:
np.sqrt(c2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## matrix multiplication --> dot product

In [69]:
A = np.array([[2,1],[3,4],[5,6]])
print(A)
print('-'*10)
B = np.array([[1,3,5],[2,4,6]])
print(B)

[[2 1]
 [3 4]
 [5 6]]
----------
[[1 3 5]
 [2 4 6]]


In [70]:
np.dot(A,B)

array([[ 4, 10, 16],
       [11, 25, 39],
       [17, 39, 61]])

## Indexing and Slicing

In [3]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = int).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print()
print(a2)
print()
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [4]:
# 1d array
a1[-2]

8

In [5]:
a1[:3]

array([0, 1, 2])

In [6]:
# negative indexing
a1[-1::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 2d array indexing and slicing

In [9]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
# method 1
a2[1,2]

6

In [11]:
# method 2
a2[1][2]

6

In [12]:
a2[1,:]

array([4, 5, 6, 7])

In [13]:
a2[:,-1]

array([ 3,  7, 11])

In [14]:
# subset of rows and columns
a2[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [15]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

## Looping numpy array

In [16]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


## Reshaping row array to column array

In [24]:
print(a1)
print(a1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [25]:
a1r = a1.reshape(-1,1)
print(a1r)
print(a1r.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


## Transpose

In [18]:
print(a2)
print()
print(a2.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Ravel --> any dimension to 1 D array

In [21]:
np.ravel(a2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## stacking

In [33]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([10,20,30,40])
c = np.array([11,22,33,44]).reshape(-1,1)
print(a)
print()
print(b)
print()
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[10 20 30 40]

[[11]
 [22]
 [33]
 [44]]


In [27]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [10, 20, 30, 40]])

In [28]:
np.hstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4

In [29]:
c = c[:-1,:]

array([[11],
       [22],
       [33]])

In [30]:
np.hstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4

In [34]:
np.column_stack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4