In [1]:
import numpy as np

## sorting

In [3]:
a = np.random.randint(1,100,15)
b = np.random.randint(-100,100,15).reshape(5,3)
print(a)
print()
print(b)

[ 2 70 94 99 13 77 12  8 64 76 41 51 43 75 90]

[[-27 -75  46]
 [-56  54 -96]
 [-78  67 -86]
 [-89 -88  63]
 [ 61  85  81]]


In [4]:
#sorting 1 d array
np.sort(a)

array([ 2,  8, 12, 13, 41, 43, 51, 64, 70, 75, 76, 77, 90, 94, 99])

In [5]:
# soring in descending
np.sort(a)[::-1]

array([99, 94, 90, 77, 76, 75, 70, 64, 51, 43, 41, 13, 12,  8,  2])

In [6]:
# sorting 2d array
np.sort(b,axis = 1)

array([[-75, -27,  46],
       [-96, -56,  54],
       [-86, -78,  67],
       [-89, -88,  63],
       [ 61,  81,  85]])

In [7]:
np.sort(b,axis = 0)

array([[-89, -88, -96],
       [-78, -75, -86],
       [-56,  54,  46],
       [-27,  67,  63],
       [ 61,  85,  81]])

## append

In [8]:
np.append(a,1000)

array([   2,   70,   94,   99,   13,   77,   12,    8,   64,   76,   41,
         51,   43,   75,   90, 1000])

In [10]:
np.append(b,1000)

array([ -27,  -75,   46,  -56,   54,  -96,  -78,   67,  -86,  -89,  -88,
         63,   61,   85,   81, 1000])

In [11]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[-27., -75.,  46.,   1.],
       [-56.,  54., -96.,   1.],
       [-78.,  67., -86.,   1.],
       [-89., -88.,  63.,   1.],
       [ 61.,  85.,  81.,   1.]])

## concatenate

In [16]:
c = np.ones((2,3))
d = np.zeros((2,3))

In [17]:
np.concatenate((c,d),axis = 1)  # rows concatenated to rows

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [18]:
np.concatenate((c,d),axis = 0)  # rows concatenated to columns

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

## unique

In [19]:
e = np.array([1,2,3,4,5,6,2,4,6,1,2,3])
len(e)

12

In [20]:
len(np.unique(e))

6

## where

In [21]:
f = np.random.randint(-10,10,8)
print(f)

[ -9   6 -10   4   9   9  -8  -5]


In [22]:
np.where(f<0)

(array([0, 2, 6, 7], dtype=int64),)

In [23]:
np.where(f<0,f**2,f)

array([ 81,   6, 100,   4,   9,   9,  64,  25])

## argmax/ argmin / argwhere

In [24]:
np.argmax(f)

4

In [26]:
np.argmin(f)

2

In [28]:
np.argwhere(f%2==0)

array([[1],
       [2],
       [3],
       [6]], dtype=int64)

In [29]:
b

array([[-27, -75,  46],
       [-56,  54, -96],
       [-78,  67, -86],
       [-89, -88,  63],
       [ 61,  85,  81]])

In [30]:
np.argmax(b,axis = 1)

array([2, 1, 1, 2, 1], dtype=int64)

## cumsum

In [31]:
wkt_per_match = np.random.randint(0,10,25)

In [32]:
wkt_per_match

array([3, 2, 1, 1, 8, 9, 1, 2, 8, 1, 1, 4, 4, 8, 1, 2, 2, 8, 3, 1, 0, 3,
       6, 1, 8])

In [33]:
cum_wkt_matchwise = np.cumsum(wkt_per_match)

In [34]:
cum_wkt_matchwise

array([ 3,  5,  6,  7, 15, 24, 25, 27, 35, 36, 37, 41, 45, 53, 54, 56, 58,
       66, 69, 70, 70, 73, 79, 80, 88])

### So, the bowler has taken 25 wickets after 25 matches

## percentile

In [40]:
marks = np.random.randint(40,100,45).reshape(3,15)
print('marks of 15 students in 3 subjects:\n',marks)

marks of 15 students in 3 subjects:
 [[68 64 43 54 44 67 95 42 98 87 47 75 62 70 75]
 [73 72 81 57 72 58 53 76 60 89 91 55 58 58 65]
 [53 52 99 65 40 50 84 72 58 70 75 89 99 58 85]]


In [41]:
# finding 50th and 90th percentile in each subject
median = np.percentile(marks,50,axis = 1)
top_marks = np.percentile(marks,90,axis = 1)
print(median)
print(top_marks)

[67. 65. 70.]
[91.8 85.8 95. ]


In [42]:
np.sort(marks,axis = 1)

array([[42, 43, 44, 47, 54, 62, 64, 67, 68, 70, 75, 75, 87, 95, 98],
       [53, 55, 57, 58, 58, 58, 60, 65, 72, 72, 73, 76, 81, 89, 91],
       [40, 50, 52, 53, 58, 58, 65, 70, 72, 75, 84, 85, 89, 99, 99]])

## histogram

In [43]:
english = marks[0,:]
print(english)

[68 64 43 54 44 67 95 42 98 87 47 75 62 70 75]


In [45]:
freq,edges = np.histogram(english,bins = 3)
print(freq)
print(edges)

[5 7 3]
[42.         60.66666667 79.33333333 98.        ]


## correlation coeffecient

In [47]:
salary = np.array([20000,40000,25000,35000,60000])
exp = np.array([1,3,2,4,2])

np.corrcoef(salary,exp)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## isin

### searches for multiples items from an existing array

In [2]:
superset = np.random.randint(1,100,30)

items = [10,20,30,40,50,60,70]

In [3]:
print(superset)
np.isin(superset,items)

[88 22 79 26 64 32 41 93 30  3  9 87 24  7  3 56 62 29 56 10 69 52 80 94
 28 98 68 38 44 84]


array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False])

In [4]:
superset[np.isin(superset,items)]

array([30, 10])

## put and insert

In [9]:
items = np.array(items)
np.put(items,[1,3],[1000,3000])

In [10]:
items

array([  10, 1000,   30, 3000,   50,   60,   70])

In [13]:
np.insert(items,[1,-1],[600,600])

array([  10,  600, 1000,   30, 3000,   50,   60,  600,   70])