**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [14]:
#Code here
a = np.ones(10)*np.nan
a[4] =1

In [15]:
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [19]:
#Code here
a = int(input('Enter nos of rows: '))
b = int(input('Enter nos of columns: '))

arr = np.random.random((a,b))
print(arr)
print()
print(np.mean(arr))

Enter nos of rows: 2
Enter nos of columns: 2
[[0.71753124 0.5700069 ]
 [0.29639286 0.22221997]]

0.45153774417081594


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [33]:
#Code here
def design(a,b):
    arr1 = np.zeros((a,b))
    arr1[:,-1] = 1
    arr1[:,0] = 1
    arr1[0,:] = 1
    arr1[-1,:] = 1
    print(arr1)

In [35]:
design(5,6)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [39]:
#Code here
b1 = np.linspace(0,1,12)
b1 = b1[1:-1]
print(b1)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

## Code here
### Identity matrix must be a square matrix

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [52]:
#Code here

#initialize a 5by5 matrix
c1 = np.zeros((5,5))
c1[:,:] = np.arange(5)
for i in c1:
    np.random.shuffle(i)
print(c1)

[[0. 4. 2. 3. 1.]
 [4. 2. 0. 3. 1.]
 [1. 4. 2. 3. 0.]
 [1. 4. 0. 2. 3.]
 [3. 4. 2. 1. 0.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [55]:
#code here
d1 = np.random.randint(1,100,size = (10,2))
point = np.array([2,3])
print(d1)
print()
print(d1 - point)

[[ 2 28]
 [69 35]
 [50 29]
 [32 36]
 [76 63]
 [61 75]
 [94 33]
 [28 82]
 [78 54]
 [19 35]]

[[ 0 25]
 [67 32]
 [48 26]
 [30 33]
 [74 60]
 [59 72]
 [92 30]
 [26 79]
 [76 51]
 [17 32]]


In [58]:
np.sqrt(np.sum((d1 - point)**2,axis = 1))

array([25.        , 74.24957912, 54.58937626, 44.59820624, 95.26804291,
       93.08598176, 96.76776323, 83.16850365, 91.5259526 , 36.23534186])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [61]:
#Code here
low = 1
high = 6*7*8 +1
e1 = np.arange(low,high)
e2 = e1.reshape(6,7,8)
print(e2)

[[[  1   2   3   4   5   6   7   8]
  [  9  10  11  12  13  14  15  16]
  [ 17  18  19  20  21  22  23  24]
  [ 25  26  27  28  29  30  31  32]
  [ 33  34  35  36  37  38  39  40]
  [ 41  42  43  44  45  46  47  48]
  [ 49  50  51  52  53  54  55  56]]

 [[ 57  58  59  60  61  62  63  64]
  [ 65  66  67  68  69  70  71  72]
  [ 73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88]
  [ 89  90  91  92  93  94  95  96]
  [ 97  98  99 100 101 102 103 104]
  [105 106 107 108 109 110 111 112]]

 [[113 114 115 116 117 118 119 120]
  [121 122 123 124 125 126 127 128]
  [129 130 131 132 133 134 135 136]
  [137 138 139 140 141 142 143 144]
  [145 146 147 148 149 150 151 152]
  [153 154 155 156 157 158 159 160]
  [161 162 163 164 165 166 167 168]]

 [[169 170 171 172 173 174 175 176]
  [177 178 179 180 181 182 183 184]
  [185 186 187 188 189 190 191 192]
  [193 194 195 196 197 198 199 200]
  [201 202 203 204 205 206 207 208]
  [209 210 211 212 213 214 215 216]
  [217 218 219 220 221

In [63]:
np.where(e2==100)

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))

In [64]:
np.argwhere(e2==100)

array([[1, 5, 3]], dtype=int64)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [67]:
#Code here
f1 = input('Enter the list of numbers space separated:')
def reverse_input(f1):
    f2 = f1.strip().split()
    f2 = [int(i) for i in f2]
    f3 = np.array(f2,dtype = 'float')
    return f3[-1::-1]

op = print('Reversed array is: ',reverse_input(f1))

Enter the list of numbers space separated:10 20 30
Reversed array is:  [30. 20. 10.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [68]:
#Code here
g1 = np.random.random((3,4,5))
np.size(g1)

60

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [69]:
#Code here
def softmax(inp):
    exp_val = np.exp(inp)
    softmax = exp_val/np.sum(exp_val)
    
    return softmax

In [71]:
h1 = np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278])
softmax(h1)

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [87]:
#Coder here
def vertical_stacks(*arr):
    return np.concatenate(arr,axis = 0)

In [88]:
a = np.arange(10).reshape(2,5)
b = np.ones((2,5))
c = b*-10
print(a)
print()
print(b)
print()
print(c)
print()
print(vertical_stacks(a,b,c))

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[-10. -10. -10. -10. -10.]
 [-10. -10. -10. -10. -10.]]

[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [  1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.]
 [-10. -10. -10. -10. -10.]
 [-10. -10. -10. -10. -10.]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [103]:
#Code here
def date_array(start = '2022-01-01', end = '2022-12-01'):
    if type(start) != str or  type(end) != str:
        raise TypeError('Requires String input')
    else:
        start = np.datetime64(start)
        end = np.datetime64(end)
        end_1 = end + np.timedelta64(1,'D')
        
        return np.arange(start,end_1)
   

In [105]:
date_array(start = '2024-01-31', end = '2024-03-03')

array(['2024-01-31', '2024-02-01', '2024-02-02', '2024-02-03',
       '2024-02-04', '2024-02-05', '2024-02-06', '2024-02-07',
       '2024-02-08', '2024-02-09', '2024-02-10', '2024-02-11',
       '2024-02-12', '2024-02-13', '2024-02-14', '2024-02-15',
       '2024-02-16', '2024-02-17', '2024-02-18', '2024-02-19',
       '2024-02-20', '2024-02-21', '2024-02-22', '2024-02-23',
       '2024-02-24', '2024-02-25', '2024-02-26', '2024-02-27',
       '2024-02-28', '2024-02-29', '2024-03-01', '2024-03-02',
       '2024-03-03'], dtype='datetime64[D]')

In [91]:
t1 = np.datetime64('2022-02-04')
t1 + np.timedelta64(1,'D')

numpy.datetime64('2022-02-05')

###`Q-14:` Subtract the mean of each row from a matrix.

In [111]:
#code here
def subtract_mean(arr):
    row_mean = np.mean(arr,axis = 1,keepdims=True)
    return arr - row_mean

In [114]:
a1 = np.array([[10,20,30,40],[100,200,300,400]])
print(a1)
print()
print(subtract_mean(a1))

[[ 10  20  30  40]
 [100 200 300 400]]

[[ -15.   -5.    5.   15.]
 [-150.  -50.   50.  150.]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [115]:
#Code here
k1 = np.arange(9).reshape(3,3)
print(k1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [116]:
k1[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

###`Q-16:` Replace odd elements in arrays with -1.

In [118]:
#Code here
q1 = np.random.randint(0,1000,size = (12,))
print(q1)
q2 = q1.copy()
q2[q2%2!=0]=-1
print(q2)

[440 803 170 218 973 671 264 721 980 668 642 277]
[440  -1 170 218  -1  -1 264  -1 980 668 642  -1]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [140]:
#Code here
def max_of_two(arr1,arr2):
    if arr1.ndim!=1 or arr2.ndim!=1:
        raise TypeError('Input arrays should be 1D')
    elif arr1.shape != arr2.shape:
        raise TypeError('Both arrays should be of same length')
    else:
        arr_temp = np.vstack((arr1,arr2))
        result = np.max(arr_temp,axis = 0)
        print(result)

In [141]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
max_of_two(a,b)

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [142]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[7799, 3728, 1054, 9032, 9626],
       [8834, 4148, 4978, 7632,  834],
       [2942, 9456, 4457, 1276, 8530],
       [2338, 6039, 2175, 6219, 7295],
       [9212, 3436,  532, 8403, 7380],
       [2062, 3364, 3157, 9857, 4940],
       [9584, 9686, 4386, 5862, 9184],
       [7372,  266, 7623, 1062, 3196]])

In [144]:
#Code here
arr2 = arr1[:,::2]

In [146]:
arr_norm = (arr2 - np.min(arr2))/(np.max(arr2) - np.min(arr2))
print(arr_norm)

[[0.79909831 0.05740048 1.        ]
 [0.91290961 0.48889378 0.03320871]
 [0.2650099  0.43160325 0.87948098]
 [0.19859248 0.18066857 0.74367715]
 [0.95447548 0.         0.75302397]
 [0.1682428  0.28865186 0.4847152 ]
 [0.99538157 0.42379591 0.95139653]
 [0.75214427 0.77974489 0.2929404 ]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [154]:
#Code here
def n_largest(arr,n):
    if arr.ndim !=1:
        raise TypeError('Not a 1D array')
    elif  n>np.size(arr):
        raise IndexError('n is larger than the array size')
    else:
        arr_sorted = np.sort(arr)
        arr_sorted = arr_sorted[::-1]
        return arr_sorted[n-1]
        

In [156]:
arr1=np.array((12,34,40,7,1,0))
n=1
n_largest(arr1,n)

40

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here